//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int Owner { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Body { get; set; }
        public Nullable<int> NoteId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> NotebookId { get; set; }
        public Nullable<int> NotecardId { get; set; }
        public Nullable<int> DeckId { get; set; }
    }
}
