//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string CardDescription { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> NotebookId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> NoteOwner { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
